<?php
echo"<pre>";
print_r($_REQUEST['nombre']."<br>");
print_r($_REQUEST['usuario']."<br>");
print_r($_REQUEST['contra']."<br>");
print_r($_REQUEST['edad']."<br>");
print_r($_REQUEST['fechanacimiento']."<br>");
print_r($_REQUEST['email']."<br>");
print_r($_REQUEST['url']."<br>");
print_r($_REQUEST['ip']."<br>");
print_r($_REQUEST['hobbies']."<br>");
print_r($_REQUEST['info']."<br>");
print_r($_REQUEST['sexo']."<br>");
print_r($_REQUEST['idioma']."<br>");
print_r($_REQUEST['cv']."<br>");
echo"</pre>";
?>